name: assign_notes_app_clean_architecture_tdd
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  fpdart: ^0.4.0
  get_it: ^7.2.0
  path: ^1.8.2
  path_provider: ^2.0.0
  sqflite: ^2.2.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  # test: ^1.16.0
  #for testing with mocks
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
